version: '3.8'

services:
  price-comparison-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bharatx-price-comparison
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - price-comparison-network

  # Development service (optional)
  price-comparison-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bharatx-price-comparison-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    command: ["npm", "run", "dev"]
    profiles:
      - dev
    networks:
      - price-comparison-network

networks:
  price-comparison-network:
    driver: bridge 