// Global e-commerce platforms that work across multiple countries
export const globalPlatforms = [
  'amazon', 'ebay', 'walmart', 'bestbuy', 'target', 'flipkart', 'snapdeal',
  'paytmmall', 'myntra', 'argos', 'currys', 'johnlewis', 'canadiantire',
  'otto', 'mediamarkt', 'saturn', 'fnac', 'darty', 'cdiscount', 'catch',
  'kogan', 'harveynorman', 'rakuten', 'yahoo', 'alibaba', 'taobao', 'jd',
  'tmall', 'pinduoduo', 'mercado', 'olx', 'gumtree', 'craigslist'
];

// Country-specific e-commerce platforms
export const countrySpecificPlatforms: { [key: string]: string[] } = {
  'US': ['amazon.com', 'walmart.com', 'bestbuy.com', 'target.com', 'ebay.com', 'newegg.com'],
  'IN': ['amazon.in', 'flipkart.com', 'snapdeal.com', 'paytmmall.com', 'myntra.com', 'ajio.com'],
  'UK': ['amazon.co.uk', 'argos.co.uk', 'currys.co.uk', 'johnlewis.com', 'ebay.co.uk', 'ao.com'],
  'CA': ['amazon.ca', 'walmart.ca', 'bestbuy.ca', 'canadiantire.ca', 'ebay.ca', 'newegg.ca'],
  'DE': ['amazon.de', 'otto.de', 'mediamarkt.de', 'saturn.de', 'ebay.de', 'idealo.de'],
  'FR': ['amazon.fr', 'fnac.com', 'darty.com', 'cdiscount.com', 'ebay.fr', 'ldlc.com'],
  'AU': ['amazon.com.au', 'ebay.com.au', 'catch.com.au', 'kogan.com', 'harveynorman.com.au', 'jbhifi.com.au'],
  'JP': ['amazon.co.jp', 'rakuten.co.jp', 'yahoo.co.jp', 'kakaku.com', 'price.com'],
  'KR': ['gmarket.co.kr', 'auction.co.kr', '11st.co.kr', 'coupang.com', 'ssg.com'],
  'CN': ['taobao.com', 'tmall.com', 'jd.com', 'pinduoduo.com', 'suning.com'],
  'BR': ['mercadolivre.com.br', 'americanas.com.br', 'magazineluiza.com.br', 'casasbahia.com.br'],
  'MX': ['mercadolibre.com.mx', 'amazon.com.mx', 'walmart.com.mx', 'coppel.com'],
  'ES': ['amazon.es', 'elcorteingles.es', 'pccomponentes.com', 'mediamarkt.es'],
  'IT': ['amazon.it', 'mediaworld.it', 'unieuro.it', 'trony.it'],
  'NL': ['amazon.nl', 'bol.com', 'coolblue.nl', 'mediamarkt.nl'],
  'SE': ['amazon.se', 'elgiganten.se', 'webhallen.com', 'inet.se'],
  'NO': ['amazon.no', 'elkjop.no', 'komplett.no', 'netonnet.no'],
  'DK': ['amazon.dk', 'elgiganten.dk', 'komplett.dk', 'proshop.dk'],
  'FI': ['amazon.fi', 'verkkokauppa.com', 'jimms.fi', 'multitronic.fi'],
  'PL': ['allegro.pl', 'amazon.pl', 'mediaexpert.pl', 'mediamarkt.pl'],
  'CZ': ['alza.cz', 'amazon.de', 'mall.cz', 'kasa.cz'],
  'HU': ['emag.hu', 'amazon.de', 'media markt.hu', 'extreme digital.hu'],
  'RO': ['emag.ro', 'amazon.de', 'altex.ro', 'flanco.ro'],
  'BG': ['emag.bg', 'amazon.de', 'technopolis.bg', 'technomarket.bg'],
  'HR': ['links.hr', 'amazon.de', 'instar-informatika.hr', 'adriatic.hr'],
  'SI': ['bigbang.si', 'amazon.de', 'funtech.si', 'harvey norman.si'],
  'SK': ['alza.sk', 'amazon.de', 'datart.sk', 'kasa.sk'],
  'EE': ['arvutitark.ee', 'amazon.de', 'k-rauta.ee', '1a.ee'],
  'LV': ['1a.lv', 'amazon.de', 'rdveikals.lv', 'elkor.lv'],
  'LT': ['1a.lt', 'amazon.de', 'pigu.lt', 'varle.lt'],
  'IE': ['amazon.co.uk', 'currys.ie', 'harvey norman.ie', 'did.ie'],
  'PT': ['amazon.es', 'worten.pt', 'fnac.pt', 'radio popular.pt'],
  'GR': ['amazon.de', 'public.gr', 'plaisio.gr', 'kotsovolos.gr'],
  'AT': ['amazon.de', 'mediamarkt.at', 'saturn.at', 'otto.at'],
  'BE': ['amazon.fr', 'mediamarkt.be', 'saturn.be', 'fnac.be'],
  'CH': ['amazon.de', 'digitec.ch', 'galaxus.ch', 'brack.ch'],
  'LU': ['amazon.fr', 'saturn.lu', 'fnac.lu', 'cora.lu'],
  'MT': ['amazon.co.uk', 'scanmalta.com', 'gadgets.com.mt'],
  'CY': ['amazon.co.uk', 'publiccy.com', 'stephanis.com.cy'],
  'RU': ['ozon.ru', 'wildberries.ru', 'yandex.ru', 'avito.ru'],
  'UA': ['rozetka.com.ua', 'prom.ua', 'olx.ua', 'hotline.ua'],
  'BY': ['21vek.by', 'oz.by', 'deal.by', 'shop.by'],
  'MD': ['999.md', 'okazii.md', 'makler.md', 'anuntul.md'],
  'GE': ['myauto.ge', 'ss.ge', 'myhome.ge', 'myphone.ge'],
  'AM': ['list.am', 'yell.am', 'bazaro.am', 'shopping.am'],
  'AZ': ['tap.az', 'bina.az', 'emlak.az', 'shopping.az'],
  'KZ': ['kaspi.kz', 'chocofamily.kz', 'daroo.kz', 'shop.kz'],
  'UZ': ['olx.uz', 'avito.uz', 'myhome.uz', 'shop.uz'],
  'KG': ['lalafo.kg', 'diesel.kg', 'shop.kg', 'market.kg'],
  'TJ': ['avito.tj', 'list.tj', 'shop.tj', 'market.tj'],
  'TM': ['avito.tm', 'list.tm', 'shop.tm', 'market.tm'],
  'AF': ['afghan-web.com', 'shop.af', 'market.af'],
  'PK': ['daraz.pk', 'olx.com.pk', 'pakwheels.com', 'pakistanstockexchange.com'],
  'BD': ['daraz.com.bd', 'ajkerdeal.com', 'rokomari.com', 'priyo.com'],
  'LK': ['daraz.lk', 'kapruka.com', 'takas.lk', 'wow.lk'],
  'NP': ['daraz.com.np', 'sastodeal.com', 'merokirana.com', 'thulo.com'],
  'BT': ['shop.bt', 'market.bt', 'online.bt'],
  'MV': ['shop.mv', 'market.mv', 'online.mv'],
  'MM': ['shop.com.mm', 'market.com.mm', 'online.com.mm'],
  'TH': ['lazada.co.th', 'shopee.co.th', 'jd.co.th', 'central.co.th'],
  'VN': ['shopee.vn', 'lazada.vn', 'tiki.vn', 'sendo.vn'],
  'LA': ['shop.la', 'market.la', 'online.la'],
  'KH': ['shop.com.kh', 'market.com.kh', 'online.com.kh'],
  'MY': ['shopee.com.my', 'lazada.com.my', '11street.my', 'lelong.com.my'],
  'SG': ['shopee.sg', 'lazada.sg', 'qoo10.sg', 'carousell.sg'],
  'ID': ['shopee.co.id', 'tokopedia.com', 'bukalapak.com', 'blibli.com'],
  'PH': ['shopee.ph', 'lazada.com.ph', 'zalora.com.ph', 'galleon.ph'],
  'TW': ['shopee.tw', 'pchome.com.tw', 'yahoo.com.tw', 'momoshop.com.tw'],
  'HK': ['shopee.com.hk', 'hk.yahoo.com', 'price.com.hk', 'openrice.com'],
  'MO': ['shop.mo', 'market.mo', 'online.mo'],
  'TR': ['trendyol.com', 'hepsiburada.com', 'n11.com', 'gittigidiyor.com'],
  'IL': ['ksp.co.il', 'zap.co.il', 'ivory.co.il', 'kravitz.co.il'],
  'AE': ['amazon.ae', 'noon.com', 'souq.com', 'desertcart.ae'],
  'SA': ['amazon.sa', 'noon.com', 'extra.com', 'jarir.com'],
  'QA': ['amazon.qa', 'noon.com', 'extra.com', 'jarir.com'],
  'KW': ['amazon.com.kw', 'noon.com', 'extra.com', 'jarir.com'],
  'BH': ['amazon.com.bh', 'noon.com', 'extra.com', 'jarir.com'],
  'OM': ['amazon.om', 'noon.com', 'extra.com', 'jarir.com'],
  'JO': ['amazon.jo', 'noon.com', 'extra.com', 'jarir.com'],
  'LB': ['amazon.com.lb', 'noon.com', 'extra.com', 'jarir.com'],
  'SY': ['amazon.sy', 'noon.com', 'extra.com', 'jarir.com'],
  'IQ': ['amazon.iq', 'noon.com', 'extra.com', 'jarir.com'],
  'IR': ['amazon.ir', 'noon.com', 'extra.com', 'jarir.com'],
  'EG': ['amazon.eg', 'noon.com', 'extra.com', 'jarir.com'],
  'LY': ['amazon.ly', 'noon.com', 'extra.com', 'jarir.com'],
  'TN': ['amazon.tn', 'noon.com', 'extra.com', 'jarir.com'],
  'DZ': ['amazon.dz', 'noon.com', 'extra.com', 'jarir.com'],
  'MA': ['amazon.ma', 'noon.com', 'extra.com', 'jarir.com'],
  'SD': ['amazon.sd', 'noon.com', 'extra.com', 'jarir.com'],
  'SS': ['amazon.ss', 'noon.com', 'extra.com', 'jarir.com'],
  'ET': ['amazon.et', 'noon.com', 'extra.com', 'jarir.com'],
  'ER': ['amazon.er', 'noon.com', 'extra.com', 'jarir.com'],
  'DJ': ['amazon.dj', 'noon.com', 'extra.com', 'jarir.com'],
  'SO': ['amazon.so', 'noon.com', 'extra.com', 'jarir.com'],
  'KE': ['amazon.ke', 'noon.com', 'extra.com', 'jarir.com'],
  'TZ': ['amazon.tz', 'noon.com', 'extra.com', 'jarir.com'],
  'UG': ['amazon.ug', 'noon.com', 'extra.com', 'jarir.com'],
  'RW': ['amazon.rw', 'noon.com', 'extra.com', 'jarir.com'],
  'BI': ['amazon.bi', 'noon.com', 'extra.com', 'jarir.com'],
  'MZ': ['amazon.mz', 'noon.com', 'extra.com', 'jarir.com'],
  'ZW': ['amazon.zw', 'noon.com', 'extra.com', 'jarir.com'],
  'ZM': ['amazon.zm', 'noon.com', 'extra.com', 'jarir.com'],
  'MW': ['amazon.mw', 'noon.com', 'extra.com', 'jarir.com'],
  'NA': ['amazon.na', 'noon.com', 'extra.com', 'jarir.com'],
  'BW': ['amazon.bw', 'noon.com', 'extra.com', 'jarir.com'],
  'LS': ['amazon.ls', 'noon.com', 'extra.com', 'jarir.com'],
  'SZ': ['amazon.sz', 'noon.com', 'extra.com', 'jarir.com'],
  'ZA': ['takealot.com', 'wootware.co.za', 'evetech.co.za', 'loot.co.za'],
  'MG': ['amazon.mg', 'noon.com', 'extra.com', 'jarir.com'],
  'MU': ['amazon.mu', 'noon.com', 'extra.com', 'jarir.com'],
  'SC': ['amazon.sc', 'noon.com', 'extra.com', 'jarir.com'],
  'KM': ['amazon.km', 'noon.com', 'extra.com', 'jarir.com'],
  'YT': ['amazon.yt', 'noon.com', 'extra.com', 'jarir.com'],
  'RE': ['amazon.re', 'noon.com', 'extra.com', 'jarir.com'],
  'AR': ['mercadolibre.com.ar', 'amazon.com.ar', 'fravega.com', 'garbarino.com'],
  'CL': ['mercadolibre.cl', 'amazon.cl', 'falabella.cl', 'paris.cl'],
  'PE': ['mercadolibre.com.pe', 'amazon.com.pe', 'falabella.com.pe', 'ripley.com.pe'],
  'CO': ['mercadolibre.com.co', 'amazon.com.co', 'falabella.com.co', 'exito.com'],
  'VE': ['mercadolibre.com.ve', 'amazon.com.ve', 'falabella.com.ve', 'exito.com.ve'],
  'EC': ['mercadolibre.com.ec', 'amazon.com.ec', 'falabella.com.ec', 'dexter.com.ec'],
  'BO': ['mercadolibre.com.bo', 'amazon.com.bo', 'falabella.com.bo', 'dexter.com.bo'],
  'PY': ['mercadolibre.com.py', 'amazon.com.py', 'falabella.com.py', 'dexter.com.py'],
  'UY': ['mercadolibre.com.uy', 'amazon.com.uy', 'falabella.com.uy', 'dexter.com.uy'],
  'GY': ['amazon.gy', 'noon.com', 'extra.com', 'jarir.com'],
  'SR': ['amazon.sr', 'noon.com', 'extra.com', 'jarir.com'],
  'GF': ['amazon.gf', 'noon.com', 'extra.com', 'jarir.com'],
  'FK': ['amazon.fk', 'noon.com', 'extra.com', 'jarir.com'],
  'GS': ['amazon.gs', 'noon.com', 'extra.com', 'jarir.com'],
  'AQ': ['amazon.aq', 'noon.com', 'extra.com', 'jarir.com'],
  'NZ': ['amazon.co.nz', 'noelleeming.co.nz', 'pbtech.co.nz', 'warehouse.co.nz'],
  'FJ': ['amazon.fj', 'noon.com', 'extra.com', 'jarir.com'],
  'PG': ['amazon.pg', 'noon.com', 'extra.com', 'jarir.com'],
  'SB': ['amazon.sb', 'noon.com', 'extra.com', 'jarir.com'],
  'VU': ['amazon.vu', 'noon.com', 'extra.com', 'jarir.com'],
  'NC': ['amazon.nc', 'noon.com', 'extra.com', 'jarir.com'],
  'PF': ['amazon.pf', 'noon.com', 'extra.com', 'jarir.com'],
  'TO': ['amazon.to', 'noon.com', 'extra.com', 'jarir.com'],
  'WS': ['amazon.ws', 'noon.com', 'extra.com', 'jarir.com'],
  'KI': ['amazon.ki', 'noon.com', 'extra.com', 'jarir.com'],
  'TV': ['amazon.tv', 'noon.com', 'extra.com', 'jarir.com'],
  'NR': ['amazon.nr', 'noon.com', 'extra.com', 'jarir.com'],
  'PW': ['amazon.pw', 'noon.com', 'extra.com', 'jarir.com'],
  'MH': ['amazon.mh', 'noon.com', 'extra.com', 'jarir.com'],
  'FM': ['amazon.fm', 'noon.com', 'extra.com', 'jarir.com'],
  'CK': ['amazon.ck', 'noon.com', 'extra.com', 'jarir.com'],
  'NU': ['amazon.nu', 'noon.com', 'extra.com', 'jarir.com'],
  'TK': ['amazon.tk', 'noon.com', 'extra.com', 'jarir.com'],
  'AS': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'GU': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'MP': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'PR': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'VI': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'AI': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'AG': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'DM': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'GD': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'LC': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'VC': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'KN': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'BB': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'TT': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'JM': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'HT': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'DO': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'CU': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'BS': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'TC': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'KY': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'BM': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'AW': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'CW': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'SX': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'BQ': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'GP': ['amazon.fr', 'noon.com', 'extra.com', 'jarir.com'],
  'MQ': ['amazon.fr', 'noon.com', 'extra.com', 'jarir.com'],
  'BL': ['amazon.fr', 'noon.com', 'extra.com', 'jarir.com'],
  'MF': ['amazon.fr', 'noon.com', 'extra.com', 'jarir.com'],
  'PM': ['amazon.fr', 'noon.com', 'extra.com', 'jarir.com'],
  'WF': ['amazon.fr', 'noon.com', 'extra.com', 'jarir.com'],
  'AD': ['amazon.es', 'noon.com', 'extra.com', 'jarir.com'],
  'MC': ['amazon.fr', 'noon.com', 'extra.com', 'jarir.com'],
  'SM': ['amazon.it', 'noon.com', 'extra.com', 'jarir.com'],
  'VA': ['amazon.it', 'noon.com', 'extra.com', 'jarir.com'],
  'LI': ['amazon.de', 'noon.com', 'extra.com', 'jarir.com'],
  'IS': ['amazon.de', 'noon.com', 'extra.com', 'jarir.com'],
  'FO': ['amazon.dk', 'noon.com', 'extra.com', 'jarir.com'],
  'GL': ['amazon.dk', 'noon.com', 'extra.com', 'jarir.com'],
  'SJ': ['amazon.no', 'noon.com', 'extra.com', 'jarir.com'],
  'AX': ['amazon.fi', 'noon.com', 'extra.com', 'jarir.com'],
  'GI': ['amazon.co.uk', 'noon.com', 'extra.com', 'jarir.com'],
  'JE': ['amazon.co.uk', 'noon.com', 'extra.com', 'jarir.com'],
  'GG': ['amazon.co.uk', 'noon.com', 'extra.com', 'jarir.com'],
  'IM': ['amazon.co.uk', 'noon.com', 'extra.com', 'jarir.com'],
  'IO': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'SH': ['amazon.co.uk', 'noon.com', 'extra.com', 'jarir.com'],
  'AC': ['amazon.co.uk', 'noon.com', 'extra.com', 'jarir.com'],
  'TA': ['amazon.co.uk', 'noon.com', 'extra.com', 'jarir.com'],
  'BV': ['amazon.no', 'noon.com', 'extra.com', 'jarir.com'],
  'HM': ['amazon.com.au', 'noon.com', 'extra.com', 'jarir.com'],
  'TF': ['amazon.fr', 'noon.com', 'extra.com', 'jarir.com'],
  'CC': ['amazon.com.au', 'noon.com', 'extra.com', 'jarir.com'],
  'CX': ['amazon.com.au', 'noon.com', 'extra.com', 'jarir.com'],
  'NF': ['amazon.com.au', 'noon.com', 'extra.com', 'jarir.com'],
  'PN': ['amazon.co.nz', 'noon.com', 'extra.com', 'jarir.com'],
  'UM': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'PS': ['amazon.com', 'noon.com', 'extra.com', 'jarir.com'],
  'EH': ['amazon.ma', 'noon.com', 'extra.com', 'jarir.com'],
  'XK': ['amazon.de', 'noon.com', 'extra.com', 'jarir.com']
};

// Domain mapping for global platforms
export const domainMapping: { [key: string]: { [key: string]: string } } = {
  'amazon': {
    'US': 'amazon.com', 'IN': 'amazon.in', 'UK': 'amazon.co.uk', 'CA': 'amazon.ca',
    'DE': 'amazon.de', 'FR': 'amazon.fr', 'AU': 'amazon.com.au', 'JP': 'amazon.co.jp',
    'IT': 'amazon.it', 'ES': 'amazon.es', 'NL': 'amazon.nl', 'SE': 'amazon.se',
    'NO': 'amazon.no', 'DK': 'amazon.dk', 'FI': 'amazon.fi', 'PL': 'amazon.pl',
    'BR': 'amazon.com.br', 'MX': 'amazon.com.mx', 'SG': 'amazon.sg', 'AE': 'amazon.ae',
    'SA': 'amazon.sa', 'TR': 'amazon.com.tr', 'EG': 'amazon.eg', 'TH': 'amazon.co.th',
    'VN': 'amazon.com.vn', 'MY': 'amazon.com.my', 'ID': 'amazon.co.id', 'PH': 'amazon.com.ph',
    'TW': 'amazon.com.tw', 'HK': 'amazon.com.hk', 'KR': 'amazon.co.kr', 'CN': 'amazon.cn'
  },
  'ebay': {
    'US': 'ebay.com', 'UK': 'ebay.co.uk', 'CA': 'ebay.ca', 'DE': 'ebay.de',
    'FR': 'ebay.fr', 'AU': 'ebay.com.au', 'IT': 'ebay.it', 'ES': 'ebay.es',
    'IE': 'ebay.ie', 'AT': 'ebay.at', 'BE': 'ebay.be', 'CH': 'ebay.ch',
    'NL': 'ebay.nl', 'PL': 'ebay.pl', 'SE': 'ebay.se', 'NO': 'ebay.no',
    'DK': 'ebay.dk', 'FI': 'ebay.fi', 'RU': 'ebay.ru', 'BR': 'ebay.com.br',
    'MX': 'ebay.com.mx', 'AR': 'ebay.com.ar', 'CL': 'ebay.cl', 'PE': 'ebay.com.pe',
    'CO': 'ebay.com.co', 'VE': 'ebay.com.ve', 'EC': 'ebay.com.ec', 'BO': 'ebay.com.bo',
    'PY': 'ebay.com.py', 'UY': 'ebay.com.uy', 'MY': 'ebay.com.my', 'SG': 'ebay.com.sg',
    'TH': 'ebay.co.th', 'VN': 'ebay.com.vn', 'ID': 'ebay.co.id', 'PH': 'ebay.com.ph',
    'TW': 'ebay.com.tw', 'HK': 'ebay.com.hk', 'IN': 'ebay.in', 'JP': 'ebay.co.jp',
    'KR': 'ebay.co.kr', 'CN': 'ebay.cn', 'AE': 'ebay.ae', 'SA': 'ebay.com.sa',
    'TR': 'ebay.com.tr', 'IL': 'ebay.co.il', 'EG': 'ebay.com.eg', 'ZA': 'ebay.co.za',
    'NZ': 'ebay.co.nz', 'FJ': 'ebay.com.fj', 'PG': 'ebay.com.pg', 'SB': 'ebay.com.sb',
    'VU': 'ebay.com.vu', 'NC': 'ebay.nc', 'PF': 'ebay.pf', 'TO': 'ebay.to',
    'WS': 'ebay.ws', 'KI': 'ebay.ki', 'TV': 'ebay.tv', 'NR': 'ebay.nr',
    'PW': 'ebay.pw', 'MH': 'ebay.mh', 'FM': 'ebay.fm', 'CK': 'ebay.ck',
    'NU': 'ebay.nu', 'TK': 'ebay.tk', 'AS': 'ebay.com', 'GU': 'ebay.com',
    'MP': 'ebay.com', 'PR': 'ebay.com', 'VI': 'ebay.com', 'AI': 'ebay.com',
    'AG': 'ebay.com', 'DM': 'ebay.com', 'GD': 'ebay.com', 'LC': 'ebay.com',
    'VC': 'ebay.com', 'KN': 'ebay.com', 'BB': 'ebay.com', 'TT': 'ebay.com',
    'JM': 'ebay.com', 'HT': 'ebay.com', 'DO': 'ebay.com', 'CU': 'ebay.com',
    'BS': 'ebay.com', 'TC': 'ebay.com', 'KY': 'ebay.com', 'BM': 'ebay.com',
    'AW': 'ebay.com', 'CW': 'ebay.com', 'SX': 'ebay.com', 'BQ': 'ebay.com',
    'GP': 'ebay.fr', 'MQ': 'ebay.fr', 'BL': 'ebay.fr', 'MF': 'ebay.fr',
    'PM': 'ebay.fr', 'WF': 'ebay.fr', 'AD': 'ebay.es', 'MC': 'ebay.fr',
    'SM': 'ebay.it', 'VA': 'ebay.it', 'LI': 'ebay.de', 'IS': 'ebay.de',
    'FO': 'ebay.dk', 'GL': 'ebay.dk', 'SJ': 'ebay.no', 'AX': 'ebay.fi',
    'GI': 'ebay.co.uk', 'JE': 'ebay.co.uk', 'GG': 'ebay.co.uk', 'IM': 'ebay.co.uk',
    'IO': 'ebay.com', 'SH': 'ebay.co.uk', 'AC': 'ebay.co.uk', 'TA': 'ebay.co.uk',
    'BV': 'ebay.no', 'HM': 'ebay.com.au', 'TF': 'ebay.fr', 'CC': 'ebay.com.au',
    'CX': 'ebay.com.au', 'NF': 'ebay.com.au', 'PN': 'ebay.co.nz', 'UM': 'ebay.com',
    'PS': 'ebay.com', 'EH': 'ebay.ma', 'XK': 'ebay.de'
  }
};

// Official brand websites for major product categories
export const officialBrands = {
  'electronics': [
    'apple.com', 'samsung.com', 'sony.com', 'lg.com', 'panasonic.com',
    'philips.com', 'sharp.com', 'toshiba.com', 'hitachi.com', 'canon.com',
    'nikon.com', 'fujifilm.com', 'gopro.com', 'dji.com', 'bose.com',
    'jbl.com', 'beats.com', 'sennheiser.com', 'shure.com', 'audio-technica.com',
    'microsoft.com', 'google.com', 'huawei.com', 'xiaomi.com', 'oneplus.com',
    'oppo.com', 'vivo.com', 'realme.com', 'motorola.com', 'nokia.com',
    'asus.com', 'acer.com', 'lenovo.com', 'dell.com', 'hp.com',
    'toshiba.com', 'msi.com', 'gigabyte.com', 'intel.com', 'amd.com',
    'nvidia.com', 'corsair.com', 'logitech.com', 'razer.com', 'steelseries.com'
  ],
  'fashion': [
    'nike.com', 'adidas.com', 'puma.com', 'reebok.com', 'underarmour.com',
    'converse.com', 'vans.com', 'newbalance.com', 'asics.com', 'skechers.com',
    'timberland.com', 'clarks.com', 'dr-martens.com', 'ugg.com', 'birkenstock.com',
    'zara.com', 'h&m.com', 'uniqlo.com', 'gap.com', 'oldnavy.com',
    'bananarepublic.com', 'jcrew.com', 'forever21.com', 'topshop.com', 'riverisland.com',
    'next.co.uk', 'marksandspencer.com', 'debenhams.com', 'houseoffraser.com',
    'selfridges.com', 'harrods.com', 'liberty.co.uk', 'farfetch.com', 'net-a-porter.com',
    'ssense.com', 'matchesfashion.com', 'luisaviaroma.com', 'mytheresa.com',
    'shopbop.com', 'revolve.com', 'asos.com', 'boohoo.com', 'prettylittlething.com'
  ],
  'home': [
    'ikea.com', 'wayfair.com', 'overstock.com', 'homedepot.com', 'lowes.com',
    'menards.com', 'acehardware.com', 'truevalue.com', 'sherwin-williams.com',
    'benjaminmoore.com', 'behr.com', 'valspar.com', 'glidden.com', 'ppg.com',
    'dulux.com', 'crownpaints.co.uk', 'farrow-ball.com', 'littlegreene.com',
    'frenchic.com', 'rust-oleum.com', 'krylon.com', 'plasti-dip.com'
  ],
  'automotive': [
    'toyota.com', 'honda.com', 'ford.com', 'chevrolet.com', 'bmw.com',
    'mercedes-benz.com', 'audi.com', 'volkswagen.com', 'volvo.com', 'saab.com',
    'subaru.com', 'mazda.com', 'nissan.com', 'mitsubishi.com', 'hyundai.com',
    'kia.com', 'lexus.com', 'infiniti.com', 'acura.com', 'buick.com',
    'cadillac.com', 'chrysler.com', 'dodge.com', 'jeep.com', 'ram.com',
    'gmc.com', 'pontiac.com', 'saturn.com', 'oldsmobile.com', 'plymouth.com'
  ],
  'beauty': [
    'sephora.com', 'ulta.com', 'macys.com', 'nordstrom.com', 'bloomingdales.com',
    'neimanmarcus.com', 'bergdorfgoodman.com', 'saksfifthavenue.com', 'barneys.com',
    'net-a-porter.com', 'farfetch.com', 'ssense.com', 'matchesfashion.com',
    'luisaviaroma.com', 'mytheresa.com', 'shopbop.com', 'revolve.com',
    'asos.com', 'boohoo.com', 'prettylittlething.com', 'missguided.com',
    'nastygal.com', 'fashionnova.com', 'prettylittlething.com', 'missguided.com'
  ],
  'sports': [
    'nike.com', 'adidas.com', 'puma.com', 'reebok.com', 'underarmour.com',
    'converse.com', 'vans.com', 'newbalance.com', 'asics.com', 'skechers.com',
    'timberland.com', 'clarks.com', 'dr-martens.com', 'ugg.com', 'birkenstock.com',
    'wilson.com', 'spalding.com', 'nikebasketball.com', 'adidasbasketball.com',
    'underarmourbasketball.com', 'reebokbasketball.com', 'pumabasketball.com'
  ]
}; 